sudo: required
services:
  - docker

before_install:
  - docker build -t mtyrpa/docker-react-training -f Dockerfile.dev .

script:
  - docker run mtyrpa/docker-react-training npm run test -- --coverage